### ISSUE TITLE
NA becomes `logical(NA)` in conversion not df

### ISSUE THREAD

**Issue by rkrug** [ropensci/openalexR#261] opened 2024-07-03 14:35 UTC
Hi

May I raise the issue again, that missing fields (experienced again with orchid) become typs=e `logical` if they are not returned from OpenAlex?

I do not have a reproducible example at the moment.

**Comment by trangdata** [comment] 2024-07-03 14:38
This is a duplicate of #220. I have labeled that issue with high priority. We will get to it soon!

**Closed by trangdata** 2024-07-03 14:38 UTC
Labels: duplicate

**Comment by rkrug** [comment] 2024-07-03 14:40
Thanks @trangdata - I looked but overlooked my own issue... Sorry. Next time I will search better.
