### ISSUE TITLE
Unstable citation network results for new publications

### ISSUE THREAD

**Issue by rkrug** [ropensci/openalexR#290] opened 2024-10-17 11:34 UTC
Hi

I am making progress with [openalexPro](https://github.com/rkrug/openalexPro/tree/main) and compatibility with `openalexR` for `oa_fetch(output = "tibble)` as well as `oa_snowball()`. But there is one problem. I implemented the snowball search based on your snowball search, and it works nicely, but I am getting, in the example I am using, one more node which is also citing a keypaper - so it is legit. Please see https://rkrug.github.io/openalexPro/inst/compatibility.html#nodes---works-retrieved-ids and below for the comparison.

As I do not see any filtering (apart de-duplication based on ids) in your code, I am at a loss where this paper get's lost?

Let me know if you need any further info,

Rainer

**Comment by rkrug** [comment] 2024-10-17 14:35
I just re rendered the cmd, and got there attached html.

[compatibility.html.zip](https://github.com/user-attachments/files/17414014/compatibility.html.zip)
 
This is frightening -10  not in openalexPro, 30 not in openalexR.

[compatibility_2.html.zip](https://github.com/user-attachments/files/17414098/compatibility_2.html.zip)

and now it is back to one paper and the same as the one you have.


Is this a caching issue on OpenAlex side? I am just re-rendering...

**Comment by yjunechoe** [comment] 2024-10-17 14:44
> Is this a caching issue on OpenAlex side? I am just re-rendering...

Perhaps! Citation networks are finnicky and volatile to the internals of the database (a problem that's not unique to OpenAlex). For any serious snowball analysis, one should download the snapshot and query it with SQL (which is what I had done in the past for a snowball software using MicrosoftAcademic).

Otherwise, I don't think this is worth looking into from openalexR's end end. There's no obvious problems with the `oa_snowball()` code and the issue doesn't even reliably replicate.

Feel free to dig in and let us know what you find here, but this doesn't seem like a bug in the package to me, so our hands are tied.

**Comment by trangdata** [comment] 2024-10-17 14:53
Hi Rainer — I'm closing the issue because this is not a bug in openalexR, but rather an inconsistency due to the newness of the paper you're analyzing in your snowball analysis. The database updates over time, and new papers may take a while to be fully integrated. We will do our best to help answer your questions as you develop your package, but please note that our time for supporting open-source projects is limited. Thanks!

**Closed by trangdata** 2024-10-17 14:53 UTC
Labels: question

**Comment by rkrug** [comment] 2024-10-18 07:41
OK - fine with me.

2 points just to throw out here:

1. this is not a problem of inconsistency due to the newness and ongoing updates, as I highlighted in https://github.com/ropensci/openalexR/issues/290#issuecomment-2419730779
2. If you do not consider your snowball function suitable for "serious snowball analysis" (whatever that is), then you should print a warning when using that function.

I just posted here to inform you about the inconsistency (and missing reference in the `oa_snowball()`approach which is present in. my implementation of the snowball search).

As a final note: I could simply develop the package(s) without having openalexR compatibility in mind (and it would make my life easier). I am just asking here, as you mentioned that openalexR is not for the power user, and I intend the package I am working on to fill that gap and to make the transition from one to the other in both directions as easy as possible.

To take your limited time budget into consideration, I will limit my interaction here to only essential posts.

Cheers,

Rainer
